server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1
    baseline-on-migrate: true
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    root: info
    ru.otus.service: DEBUG
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
        jdbc.core.JdbcTemplate: info
        web: DEBUG
      thymeleaf: DEBUG