server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1
    baseline-on-migrate: true


logging:
  level:
    root: debug
    ru.otus.service: DEBUG
    org:
      springframework:
        transaction: DEBUG
        jdbc.core.JdbcTemplate: DEBUG
        web: DEBUG
      thymeleaf: DEBUG